apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-rds-certs
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: aws-rds-certs
  data:
  - secretKey: ap-northeast-1-bundle.pem
    remoteRef:
      key: secret/aws-rds-certs
      property: ap-northeast-1-bundle